import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import './globals.css'
import Provider from './(Providers)/NextUiProviders'
import { Inter, Montserrat } from "next/font/google";

const inter = Inter({ subsets: ['latin'],variable:'--font-inter' })

const monserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: 'Becodemy AI Prompt Marketplace',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${inter.variable} ${monserrat.variable}`}>
            <Provider>
              {children}
                </Provider>
        </body>
    </html>
    </ClerkProvider> 
  )
}
